task_description = """\
# Task Description
You will be responsible for identifying whether error reports are false positives. \
The error reports generated by static analysis tools will be provided to you, including reports from SPOTBUGS for Java projects and reports from CPPCHECK, INFER, and CSA for C/C++ projects.\
Your task is to verify the bug's existence and classify them as either real bug or false alarm.\
In the last line of your answer, you should conclude with either '@@@ real bug @@@', '@@@ false alarm @@@', or '@@@ unknown @@@'.\n
"""

reinforce = """\
Remember, you're the best AI patch analyst and will use your expertise to provide the best possible analysis.\
"""

task_confirmation = """\
Got it?
"""

positive_feedback = """\
Great! Let's begin the task.
"""
