few_shot_example1 = """\

# example1
# Bug Report
```json
{
    "categpry": "I18N",
    "vtype": "DM_DEFAULT_ENCODING",
    "priority": "1",
    "rank": "19",
    "project": "commons-configuration",
    "origin commit": "a3533f91fc22d286131cf475de6bdad498a3c8d3",
    "buggy commit": "86c68c3a3f73a62e9a21d3f5cb692099d52f1fc4",
    "buggy path": "src/main/java/org/apache/commons/configuration2/plist/XMLPropertyListConfiguration.java",
    "buggy start": "412",
    "buggy end": "412",
    "fixer": "997f50595fd7b2df1730c7d4f9a0332ae9aad9f6",
    "fixer path": "src/main/java/org/apache/commons/configuration2/plist/XMLPropertyListConfiguration.java",
    "method": "printValue(Ljava/io/PrintWriter;ILjava/lang/Object;)V",
    "field": "NO_FIELD",
    "resolution": "fixed",
    "life_time": "217",
    "mark-all": "TP",
    "Kind": "Private Method",
    "Name": "org.apache.commons.configuration2.plist.PropertyListConfiguration.printValue(PrintWriter,int,Object)",
    "File": "main\\java\\org\\apache\\commons\\configuration2\\plist\\PropertyListConfiguration.java",
    "AvgCyclomatic": "-1",
    "AvgCyclomaticModified": "-1",
    "AvgCyclomaticStrict": "-1",
    "AvgEssential": "-1",
    "AvgLine": "-1",
    "AvgLineBlank": "-1",
    "AvgLineCode": "-1",
    "AvgLineComment": "-1",
    "CountClassBase": "-1",
    "CountClassCoupled": "-1",
    "CountClassCoupledModified": "-1",
    "CountClassDerived": "-1",
    "CountDeclClass": "-1",
    "CountDeclClassMethod": "-1",
    "CountDeclClassVariable": "-1",
    "CountDeclExecutableUnit": "-1",
    "CountDeclFile": "-1",
    "CountDeclFunction": "-1",
    "CountDeclInstanceMethod": "-1",
    "CountDeclInstanceVariable": "-1",
    "CountDeclMethod": "-1",
    "CountDeclMethodAll": "-1",
    "CountDeclMethodDefault": "-1",
    "CountDeclMethodPrivate": "-1",
    "CountDeclMethodProtected": "-1",
    "CountDeclMethodPublic": "-1",
    "CountInput": "5",
    "CountLine": "67",
    "CountLineBlank": "2",
    "CountLineCode": "60",
    "CountLineCodeDecl": "12",
    "CountLineCodeExe": "35",
    "CountLineComment": "5",
    "CountOutput": "23",
    "CountPath": "11",
    "CountPathLog": "1",
    "CountSemicolon": "23",
    "CountStmt": "34",
    "CountStmtDecl": "10",
    "CountStmtExe": "24",
    "Cyclomatic": "11",
    "CyclomaticModified": "11",
    "CyclomaticStrict": "11",
    "Essential": "1",
    "Knots": "6",
    "MaxCyclomatic": "-1",
    "MaxCyclomaticModified": "-1",
    "MaxCyclomaticStrict": "-1",
    "MaxEssential": "-1",
    "MaxEssentialKnots": "0",
    "MaxInheritanceTree": "-1",
    "MaxNesting": "3",
    "MinEssentialKnots": "0",
    "PercentLackOfCohesion": "-1",
    "PercentLackOfCohesionModified": "-1",
    "RatioCommentToCode": "0.08",
    "SumCyclomatic": "11",
    "SumCyclomaticModified": "11",
    "SumCyclomaticStrict": "11",
    "SumEssential": "1",
    "location_count": "2",
    "method_count": "10",
    "file_count": "88"
}
```

## Your Answer
@@@ actionable @@@
"""



few_shot_example2 = """\

# example2
# Bug Report
```json
{
    "categpry": "DODGY_CODE",
    "vtype": "DLS_DEAD_LOCAL_STORE",
    "priority": "3",
    "rank": "20",
    "project": "commons-net",
    "origin commit": "4379a6810227bf2eeba5860b62d42834d62e4413",
    "buggy commit": "ab45bdb289e3929d71501008099c0e890653d7ab",
    "buggy path": "src/main/java/org/apache/commons/net/tftp/TFTPClient.java",
    "buggy start": "388",
    "buggy end": "388",
    "fixer": "41e514cda5f68c444edc1058a18e2196b2c1d7d5",
    "fixer path": "src/main/java/org/apache/commons/net/tftp/TFTPClient.java",
    "method": "sendFile(Ljava/lang/String;ILjava/io/InputStream;Ljava/net/InetAddress;I)V",
    "field": "NO_FIELD",
    "resolution": "fixed",
    "life_time": "2312",
    "mark-all": "TP",
    "Kind": "Public Method",
    "Name": "org.apache.commons.net.tftp.TFTPClient.sendFile(String,int,InputStream,InetAddress)",
    "File": "main\\java\\org\\apache\\commons\\net\\tftp\\TFTPClient.java",
    "AvgCyclomatic": "-1",
    "AvgCyclomaticModified": "-1",
    "AvgCyclomaticStrict": "-1",
    "AvgEssential": "-1",
    "AvgLine": "-1",
    "AvgLineBlank": "-1",
    "AvgLineCode": "-1",
    "AvgLineComment": "-1",
    "CountClassBase": "-1",
    "CountClassCoupled": "-1",
    "CountClassCoupledModified": "-1",
    "CountClassDerived": "-1",
    "CountDeclClass": "-1",
    "CountDeclClassMethod": "-1",
    "CountDeclClassVariable": "-1",
    "CountDeclExecutableUnit": "-1",
    "CountDeclFile": "-1",
    "CountDeclFunction": "-1",
    "CountDeclInstanceMethod": "-1",
    "CountDeclInstanceVariable": "-1",
    "CountDeclMethod": "-1",
    "CountDeclMethodAll": "-1",
    "CountDeclMethodDefault": "-1",
    "CountDeclMethodPrivate": "-1",
    "CountDeclMethodProtected": "-1",
    "CountDeclMethodPublic": "-1",
    "CountInput": "5",
    "CountLine": "17",
    "CountLineBlank": "0",
    "CountLineCode": "6",
    "CountLineCodeDecl": "3",
    "CountLineCodeExe": "1",
    "CountLineComment": "11",
    "CountOutput": "1",
    "CountPath": "1",
    "CountPathLog": "0",
    "CountSemicolon": "1",
    "CountStmt": "2",
    "CountStmtDecl": "1",
    "CountStmtExe": "1",
    "Cyclomatic": "1",
    "CyclomaticModified": "1",
    "CyclomaticStrict": "1",
    "Essential": "1",
    "Knots": "0",
    "MaxCyclomatic": "-1",
    "MaxCyclomaticModified": "-1",
    "MaxCyclomaticStrict": "-1",
    "MaxEssential": "-1",
    "MaxEssentialKnots": "0",
    "MaxInheritanceTree": "-1",
    "MaxNesting": "0",
    "MinEssentialKnots": "0",
    "PercentLackOfCohesion": "-1",
    "PercentLackOfCohesionModified": "-1",
    "RatioCommentToCode": "1.83",
    "SumCyclomatic": "1",
    "SumCyclomaticModified": "1",
    "SumCyclomaticStrict": "1",
    "SumEssential": "1",
    "location_count": "6",
    "method_count": "18",
    "file_count": "18"
}
```

## Your Answer
@@@ actionable @@@
"""

few_shot_example3 = """\

# example3
## Bug Report
```json
{
    "categpry": "BAD_PRACTICE",
    "vtype": "DE_MIGHT_IGNORE",
    "priority": "3",
    "rank": "19",
    "project": "commons-pool",
    "origin commit": "4f9912974fff05b614e6c81bb4d862fcfb552c3d",
    "buggy commit": "a28d908dd2087d47137953952dbae83c0f48e3b7",
    "buggy path": "src/main/java/org/apache/commons/pool2/PoolUtils.java",
    "buggy start": "1481",
    "buggy end": "1481",
    "fixer": "",
    "fixer path": "",
    "method": "invalidateObject(Ljava/lang/Object;)V",
    "field": "NO_FIELD",
    "resolution": "unfixed",
    "life_time": "747",
    "mark-all": "FP",
    "marked-human": "",
    "Kind": "Public Abstract Method",
    "Name": "org.apache.commons.pool2.BaseObjectPool.invalidateObject(T)",
    "File": "java\\org\\apache\\commons\\pool2\\BaseObjectPool.java",
    "AvgCyclomatic": "-1",
    "AvgCyclomaticModified": "-1",
    "AvgCyclomaticStrict": "-1",
    "AvgEssential": "-1",
    "AvgLine": "-1",
    "AvgLineBlank": "-1",
    "AvgLineCode": "-1",
    "AvgLineComment": "-1",
    "CountClassBase": "-1",
    "CountClassCoupled": "-1",
    "CountClassCoupledModified": "-1",
    "CountClassDerived": "-1",
    "CountDeclClass": "-1",
    "CountDeclClassMethod": "-1",
    "CountDeclClassVariable": "-1",
    "CountDeclExecutableUnit": "-1",
    "CountDeclFile": "-1",
    "CountDeclFunction": "-1",
    "CountDeclInstanceMethod": "-1",
    "CountDeclInstanceVariable": "-1",
    "CountDeclMethod": "-1",
    "CountDeclMethodAll": "-1",
    "CountDeclMethodDefault": "-1",
    "CountDeclMethodPrivate": "-1",
    "CountDeclMethodProtected": "-1",
    "CountDeclMethodPublic": "-1",
    "CountInput": "0",
    "CountLine": "13",
    "CountLineBlank": "0",
    "CountLineCode": "1",
    "CountLineCodeDecl": "1",
    "CountLineCodeExe": "0",
    "CountLineComment": "12",
    "CountOutput": "0",
    "CountPath": "0",
    "CountPathLog": "0",
    "CountSemicolon": "1",
    "CountStmt": "1",
    "CountStmtDecl": "1",
    "CountStmtExe": "0",
    "Cyclomatic": "0",
    "CyclomaticModified": "0",
    "CyclomaticStrict": "0",
    "Essential": "0",
    "Knots": "0",
    "MaxCyclomatic": "-1",
    "MaxCyclomaticModified": "-1",
    "MaxCyclomaticStrict": "-1",
    "MaxEssential": "-1",
    "MaxEssentialKnots": "0",
    "MaxInheritanceTree": "-1",
    "MaxNesting": "0",
    "MinEssentialKnots": "0",
    "PercentLackOfCohesion": "-1",
    "PercentLackOfCohesionModified": "-1",
    "RatioCommentToCode": "12",
    "SumCyclomatic": "0",
    "SumCyclomaticModified": "0",
    "SumCyclomaticStrict": "0",
    "SumEssential": "0",
    "location_count": "13",
    "method_count": "24",
    "file_count": "168"
}
```

## Your Answer
@@@ unactionable @@@
"""


few_shot_example4 = """\

# example4
# Bug Report
```json
{
    "categpry": "DODGY_CODE",
    "vtype": "UUF_UNUSED_PUBLIC_OR_PROTECTED_FIELD",
    "priority": "2",
    "rank": "17",
    "project": "maven-dependency-plugin",
    "origin commit": "dd1f45c161553b92a245aa52cf2839a3ffb7bb74",
    "buggy commit": "d6b4b575fb251c418f5f6438419648b4690191de",
    "buggy path": "src/main/java/org/apache/maven/plugin/dependency/AbstractDependencyMojo.java",
    "buggy start": "-1",
    "buggy end": "-1",
    "fixer": "",
    "fixer path": "",
    "method": "NO_METHOD",
    "field": "reactorProjects",
    "resolution": "unfixed",
    "life_time": "372",
    "mark-all": "FP",
    "Kind": "Public Abstract Class",
    "Name": "org.apache.maven.plugin.dependency.AbstractDependencyMojo",
    "AvgCyclomatic": "1",
    "AvgCyclomaticModified": "1",
    "AvgCyclomaticStrict": "1",
    "AvgEssential": "1",
    "AvgLine": "12",
    "AvgLineBlank": "0",
    "AvgLineCode": "7",
    "AvgLineComment": "4",
    "CountClassBase": "1",
    "CountClassCoupled": "1",
    "CountClassCoupledModified": "1",
    "CountClassDerived": "2",
    "CountDeclClass": "-1",
    "CountDeclClassMethod": "0",
    "CountDeclClassVariable": "0",
    "CountDeclExecutableUnit": "-1",
    "CountDeclFile": "-1",
    "CountDeclFunction": "-1",
    "CountDeclInstanceMethod": "20",
    "CountDeclInstanceVariable": "12",
    "CountDeclMethod": "20",
    "CountDeclMethodAll": "20",
    "CountDeclMethodDefault": "0",
    "CountDeclMethodPrivate": "1",
    "CountDeclMethodProtected": "3",
    "CountDeclMethodPublic": "16",
    "CountInput": "-1",
    "CountLine": "366",
    "CountLineBlank": "45",
    "CountLineCode": "164",
    "CountLineCodeDecl": "41",
    "CountLineCodeExe": "58",
    "CountLineComment": "157",
    "CountOutput": "-1",
    "CountPath": "-1",
    "CountPathLog": "-1",
    "CountSemicolon": "53",
    "CountStmt": "82",
    "CountStmtDecl": "37",
    "CountStmtExe": "45",
    "Cyclomatic": "-1",
    "CyclomaticModified": "-1",
    "CyclomaticStrict": "-1",
    "Essential": "-1",
    "Knots": "-1",
    "MaxCyclomatic": "7",
    "MaxCyclomaticModified": "7",
    "MaxCyclomaticStrict": "8",
    "MaxEssential": "1",
    "MaxEssentialKnots": "-1",
    "MaxInheritanceTree": "2",
    "MaxNesting": "3",
    "MinEssentialKnots": "-1",
    "PercentLackOfCohesion": "91",
    "PercentLackOfCohesionModified": "88",
    "RatioCommentToCode": "0.96",
    "SumCyclomatic": "30",
    "SumCyclomaticModified": "30",
    "SumCyclomaticStrict": "31",
    "SumEssential": "20",
    "location_count": "19",
    "method_count": "59",
    "file_count": "192"
}
```

## Your Answer
@@@ unactionable @@@
"""